# # this file is a configuration file for github actions
# # it performs various checks on the codebase
# ---
# name: Checks # This workflow is named "Checks" and is triggered on every push event to the repository.

# on: [push]

# jobs:
#   test-lint: # This workflow defines a single job named "test-lint" that runs on an ubuntu-20.04 environment.
#     name: Test and Lint
#     runs-on: ubuntu-20.04 # GitHub action is preinstalled on this ubunutu environment
#     steps:
#       - name: Login to Docker Hub #  action to login to Docker Hub.
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKERHUB_USER }}
#           password: ${{ secrets.DOCKERHUB_SECRET }}
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Test
#         uses: docker/compose@v1
#         with:
#           run: docker compose run --rm app sh -c "python manage.py test"

---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_SECRET }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"
